name: Refresh go report card

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '40 12 1 * *'
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  post-request:
    name: Call refresh go report card action
    uses: andrew-field/reusable-workflows/.github/workflows/refresh-go-report-card.yml@master
